# Generated by Django 3.0.3 on 2020-03-09 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedatabaseform',
            name='bloodGroup',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='employeedatabaseform',
            name='dateOfBirth',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='employeedatabaseform',
            name='designation',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='employeedatabaseform',
            name='empContact',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='employeedatabaseform',
            name='maritalStatus',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='employeedatabaseform',
            name='sex',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='employeedatabaseform',
            name='spouseName',
            field=models.CharField(max_length=20),
        ),
    ]
