# Generated by Django 3.0.3 on 2020-03-09 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrApp', '0002_auto_20200309_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedatabaseform',
            name='dateOfBirth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='employeedatabaseform',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6),
        ),
    ]
