# Generated by Django 3.0.3 on 2020-03-09 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrApp', '0003_auto_20200309_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedatabaseform',
            name='maritalStatus',
            field=models.CharField(choices=[('Married', 'Married'), ('Widowed', 'Widowed'), ('Separated', 'Separated'), ('Divorced', 'Divorced'), ('Single', 'Single')], default='Single', max_length=10),
        ),
    ]
