# Generated by Django 3.0.3 on 2020-03-05 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empId', models.CharField(max_length=20)),
                ('empName', models.CharField(max_length=20)),
                ('empEmail', models.EmailField(max_length=200)),
                ('empContact', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'employeeApp',
            },
        ),
    ]
